#!/bin/sh
if [ -n "$(pidof kdm)" ]; then
    exec kdmctl reserve "$@"
elif [ -n "$(pidof gdm)" ]; then
    exec gdmflexiserver -ls "$@"
else
    echo "No known DM running, maybe we're using startx"
    exit 1
fi
